name: 저장용블로그
title: 저장용블로그
description: //
tags:
  - java
  - python
  - economics
  - statistics
  - netlify
  - Programming_etc
show_hero: true
menu:
  - title: Home
    url: /
  #
  - title: ・・・・
    url: /Programming_java.xml
  - title: java
    url: /Programming_java.xml
  - title: python
    url: /Programming_python.xml
  - title: 経済学
    url: /economics.xml
  - title: 統計学
    url: /statistics.xml
  - title: .etc
    url: /Programming_etc.xml
  #
  - title: ・・・・
    url: /about
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: yong8812@naver.com
# See: https://disqus.com/
disqus_username: HwangYong
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
